// Each #kernel tells which function to compile; you can have many kernels
#pragma kernel CSMain
#pragma target 5.0

RWStructuredBuffer<float> ResultBuffer;
StructuredBuffer<float2> octaveOffsets;

int width;
int height;
float scale;
int seed;
int octaves;
float persistence;
float lacunarity;
float xOffset;
float yOffset;

//random value generator
float2 hash2(float2 position)
{
    return frac(sin(float2(dot(position, float2(127.1, 311.7)), dot(position, float2(269.5, 183.3)))) * 43758.5453);
}

//interpolation curve (Perlin's fade function)
float fade(float t) {
    return t * t * t * (t * (t * 6 - 15) + 10); //6*t^5 - 15*t^4 + 10*t^3;
}

//linear interpolation
float lerp(float a, float b, float t)
{
    return a + t * (b - a);
}

float perlin(float2 pt)
{
  float2 cell = floor(pt); 
  float2 local = frac(pt);

  //gradients -- generate random vectors for each corner, map between[0,1) & normalize
  float2 g00 = normalize(hash2(cell + float2(0.0, 0.0)) * 2.0 - 1.0); //bottom-left
  float2 g10 = normalize(hash2(cell + float2(1.0, 0.0)) * 2.0 - 1.0); //bottom-right
  float2 g01 = normalize(hash2(cell + float2(0.0, 1.0)) * 2.0 - 1.0); //top-left
  float2 g11 = normalize(hash2(cell + float2(1.0, 1.0)) * 2.0 - 1.0); //top-right

  //displacements
  float2 d00 = local - float2(0.0, 0.0);
  float2 d10 = local - float2(1.0, 0.0);
  float2 d01 = local - float2(0.0, 1.0);
  float2 d11 = local - float2(1.0, 1.0);

  //dot products between gradients and displacements
  float s = dot(g00, d00);
  float t = dot(g10, d10);
  float u = dot(g01, d01);
  float v = dot(g11, d11);

  //interpolate dot product using the fade function
  float fx = fade(local.x);
  float fy = fade(local.y); //smoothed distance from x/y-axis 

  //bilinear interpolation
  float i1 = lerp(s, t, fx);
  float i2 = lerp(u, v, fx); //=>smooth continuous noise

  return lerp(i1, i2, fy);

}

float fractal(float2 pos){
    float total = 0.0;
    float frequency = 1.0;
    float amplitude = 1.0;
    float maxValue = 0.0;

    for (int i = 0; i < octaves; i++) {
        float2 samplePos = ((pos + octaveOffsets[i]) / scale) * frequency;
        total += perlin(samplePos) * amplitude;
        maxValue += amplitude;
        amplitude *= persistence;
        frequency *= lacunarity;
    }

    return total / maxValue;
}

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_DispatchThreadID)
{
    if (id.x >= (uint)width || id.y >= (uint)height) return;

    float2 pixelPos = float2(id.x, id.y);
    float2 centerOffset = float2(width, height) * 0.5;
    float2 uv = pixelPos - centerOffset;

    float val = fractal(uv); 

    uint index = id.y * (uint)width + id.x;
    ResultBuffer[index] = saturate(val); //clamp to [0,1]
}